Unity-Technologies/multiplayer-community-contributions

LiteNetLibTransport/LiteNetLibTransport.cs
LiteNetLibTransport/LiteNetLibTransport.csproj
MLAPI.Transports.sln
appveyor.yml
artifact_paths.json

Here's my attempt at adding LiteNetLib to the repo.  I have no idea how projects and builds and such work in .NET so it's all monkey-see monkey-do.  I'll be amazed if it works without needing you to make any fixes.
And of course, you can have fun reformatting the source code.  :)

Add LiteNetLib transport.

---

README.md
com.mlapi.contrib.extensions/Runtime/NetworkManagerHud/NetworkManagerHud.cs

Will upgrade this or potentially move to core lib when my RFC + PR about extending transport interface passes

feat: Add a network manager hud using UNet transport

---

Transports/com.mlapi.contrib.transport.steamp2p/Runtime/SteamManager.cs
Transports/com.mlapi.contrib.transport.steamp2p/Runtime/SteamManager.cs.meta

A lot of people will use this as it is included with the default Unity Package but not the dll so adding it here.

feature: Add steammanager to steam transport

---

Transports/com.mlapi.contrib.transport.litenetlib/Runtime/LiteNetLibTransport.cs

fix: Fix null ref exception when shut down litenetlib without initializing.

---

Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/Photon/PhotonRealtime/Code/Unity/Editor/AccountService.cs
Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/Photon/PhotonRealtime/Code/Unity/Editor/Wizard/scripts/WizardWindow.cs

This is just a small change for our statistics of account registration.

ADDED: An "origin" asset version for registration requests.

---

Transports/com.mlapi.contrib.transport.enet/Runtime/EnetTransport.cs

This is only due to rename, should not happen again as future PRs will be towards main

merge master to main

---

README.md
Transports/com.mlapi.contrib.transport.facepunch/Runtime/ReadOnlyAttribute.cs

- Wrap editor code in ifdefs to allow for builds
-  Add facepunch transport to readme

fix: facepunch cleanup

---

Transports/com.mlapi.contrib.transport.litenetlib/Runtime/LiteNetLibTransport.cs

The latest Transport removed the notion of NetworkChannel.

feat: update litenetlib to latest transport API

---

README.md

Added NetworkRigidBody2D to the extensions table in the main README.

Updated main README.md for NetworkRigidBody2D

---

Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/PhotonRealtimeTransport.Connection.cs
Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/PhotonRealtimeTransport.cs

Updates the photon transport to the latest API changes in the develop branch.
Channels have been removed and replaced with NetworkDelivery.

feat: Update photon transport to latest API changes.

---

Transports/com.community.netcode.transport.websocket/Runtime/JSWebSocketClient.cs
Transports/com.community.netcode.transport.websocket/Runtime/JSWebSocketClient.jslib
Transports/com.community.netcode.transport.websocket/Runtime/WebSocketTransport.cs

fix: replace usages of MLAPI with Netcode in js part

---

README.md

docs: update readme to link to to the steamnetworking transport

---

com.community.netcode.extensions/Runtime/NetworkDiscovery/NetworkDiscovery.cs

NetworkDiscovery had some bugs starting from the upgrade to the 1.0.0 version, this PR fixes those bugs.
Fixes #126
Fixes #115

fix: NetworkDiscovery WriteSafety

---

com.community.netcode.extensions/Runtime/com.community.contrib.extensions.asmdef

Extension package reference UTP so that NetworkEndPoint is referenced.

fix: reference UTP

---

Transports/com.community.netcode.transport.photon-realtime/Runtime/PhotonRealtimeTransport.Connection.cs

fix: prevent reconnection cancelation (#166)

---

com.community.netcode.extensions/Runtime/ClientNetworkAnimator/ClientNetworkAnimator.cs
com.community.netcode.extensions/Runtime/ClientNetworkAnimator/README.md

A simple script modified from the official ``NetworkAnimator``.
It brings a very easy way to sync animation info from client to server.

Feat: client network animator

---

Transports/com.community.netcode.transport.websocket/Runtime/WebSocketTransport.cs

Added support to allow port forwarding on the server, secure connection on any port on the server and assign SSL certificate with a base64 string.

WebSocket server properties exposed

---

Transports/com.community.netcode.transport.websocket/Runtime/WebSocketTransport.cs

fixes #205 and similar to #199

fix null reference exception in web socket transport when closing a host

---

com.community.netcode.extensions/Runtime/ClientNetworkAnimator/README.md

Updated README. Adding guide to the official approach for a client auth animator.

Update README.md for ClientNetworkAnimator

---

com.community.netcode.extensions/Runtime/NetworkObjectPool/NetworkObjectPool.cs

NetworkObjectPool: Removed extra closing brace

---

Transports/com.community.netcode.transport.facepunch/Runtime/FacepunchTransport.cs

workaround/possible fix:
https://github.com/Unity-Technologies/multiplayer-community-contributions/issues/245

Workround for reported issue when a client is disconnected
