Unity-Technologies/multiplayer-community-contributions

LiteNetLibTransport/LiteNetLibTransport.cs
I was trying to implement the LiteNetLib transport, but I was never receiving any events. I finally realized that `NetManager.PollEvents()` was never called anywhere. It's my understanding that has to happen in order to receive events unless you use `UnsyncedEvents`. 
Neither of these were true so no events were able to be processed from the MLAPI side. The comments say to call `PollEvents `in the update function, so that's just where I put it. Open to better suggestions.
=> LiteNetLib - Call PollEvents on Update so MLAPI can access events.

RufflesTransport/RufflesTransport.cs
when accessing custom channels defined in the unity editor during socket configuration creation the Channels list was used with a wrong index i, which started at 7 (number of channels of MLAPI_CHANNELS) instead of 0.
=> fix: wrong array index for custom channel

SteamP2PTransport/SteamP2PTransport.cs
This PR updates the SteamP2PTransport to the newest version of MLAPI by replacing the LogHelper calls with the new NetworkLog API.
=> feat: Update SteamP2PTransport to v12.1.7

Transports/com.mlapi.contrib.transport.enet/Runtime/EnetTransport.cs, Transports/com.mlapi.contrib.transport.enet/Runtime/com.mlapi.contrib.transport.enet.asmdef, Transports/com.mlapi.contrib.transport.litenetlib/Runtime/LiteNetLibTransport.cs, Transports/com.mlapi.contrib.transport.litenetlib/Runtime/com.mlapi.contrib.transport.litenet.asmdef, Transports/com.mlapi.contrib.transport.ruffles/CHANGELOG.md.meta, Transports/com.mlapi.contrib.transport.ruffles/LICENSE.meta, Transports/com.mlapi.contrib.transport.ruffles/README.md.meta, Transports/com.mlapi.contrib.transport.ruffles/Runtime/Ruffles/AssemblyInfo.cs, Transports/com.mlapi.contrib.transport.ruffles/Runtime/Ruffles/Ruffles.csproj, Transports/com.mlapi.contrib.transport.ruffles/Runtime/RufflesTransport.cs, Transports/com.mlapi.contrib.transport.ruffles/Runtime/com.mlapi.contrib.transport.ruffles.asmdef, Transports/com.mlapi.contrib.transport.ruffles/package.json.meta, Transports/com.mlapi.contrib.transport.steamp2p/Runtime/SteamP2PTransport.cs, Transports/com.mlapi.contrib.transport.steamp2p/Runtime/com.mlapi.contrib.transport.steamp2p.asmdef, Transports/com.mlapi.contrib.transport.template/CHANGELOG.md.meta, Transports/com.mlapi.contrib.transport.template/LICENSE.meta, Transports/com.mlapi.contrib.transport.template/README.md.meta, Transports/com.mlapi.contrib.transport.template/Runtime.meta, Transports/com.mlapi.contrib.transport.template/Runtime/TemplateTransport.cs, Transports/com.mlapi.contrib.transport.template/Runtime/com.mlapi.contrib.transport.template.asmdef, Transports/com.mlapi.contrib.transport.template/Runtime/com.mlapi.contrib.transport.template.asmdef.meta, Transports/com.mlapi.contrib.transport.template/package.json.meta
This auto references the transport assemblies so that they can be used in user code. I also took the chance to adjust namespaces to a common format.
Update the transport template to the newest version.
=> Fix transport namespaces and auto reference asmdefs

Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/PhotonRealtimeTransport.cs
Passing the default ArraySegment with underlying array of null to Photon Realtime is not supported.
Start host in editor + 1 build client. Leave playmode as the host while client is still connected. Exception gets thrown.
```
ArgumentNullException: Value cannot be null.
Parameter name: src
System.Buffer.BlockCopy (System.Array src, System.Int32 srcOffset, System.Array dst, System.Int32 dstOffset, System.Int32 count) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
ExitGames.Client.Photon.StreamBuffer.Write (System.Byte[] buffer, System.Int32 srcOffset, System.Int32 count) (at <7a1610b16458477ca115d303bf8d4590>:0)
ExitGames.Client.Photon.Protocol18.WriteArraySegmentByte (ExitGames.Client.Photon.StreamBuffer stream, System.ArraySegment1[T] seg, System.Boolean writeType) (at …
```
=> fix: Fixes the function used to disconnect remote clients.

Transports/com.mlapi.contrib.transport.steamp2p/Runtime/Steamworks.NET/Windows-x64/Steamworks.NET.dll.meta, Transports/com.mlapi.contrib.transport.steamp2p/Runtime/Steamworks.NET/Windows-x86/Steamworks.NET.dll.meta
Fixes #42 
Fixes a bug which caused a build with SteamP2PTransport to fail on all platforms.
I tested that building on the following platforms works now:
- windows x86_64
- linux x86_64
- macOs intel 64-bit + Apple silicon
=> fix: Fix managed plugin settings for windows platform dlls

Transports/com.mlapi.contrib.transport.enet/Runtime/EnetTransport.cs
When shutting down the Enet transport, EnetTransport.host.Dispose() is called, which shuts down all internal things. However, the host variable is not explicity set to null. 
This leads to an issue when shutting down, as Update() checks for host?.Flush(), which gets executed due to host not being null. 
Explicity setting host = null fixes this issue, but there might be more elegant ways too.
=> Fix: EnetTransport shutdown - explicitly set host to null to prevent error spam. 

Transports/com.mlapi.contrib.transport.enet/Runtime/EnetTransport.cs
fixes #45
This is a Enet transport specific issue which had to be fixed in the transport. Peers are now cleared correctly when shutting down allowing for multiple sessions in the same application.
=> fix: Fix a bug where enet transport does not clear peers on shutdown

com.mlapi.contrib.extensions/Runtime/NetworkRigidbody/NetworkRigidbody.cs
NetworkVariableSettingsUtility has been merged by accident into the contrib repo and prevent the extension package from compiling.
=> fix: Remove missing NetworkVariableSettingsUtility references

Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/Photon/PhotonRealtime/Code/Unity/Editor/Wizard/scripts/WizardWindow.cs, Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/PhotonRealtimeTransport.Matchmaking.cs, Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/PhotonRealtimeTransport.cs
This should fix issue #69, #70 and #71.
As the m_Client can be set to null, we needed a few more null checks. 
I also added a simple limitation to datagrams being sent in a single frame. This might prevent local networking issues when the send queues have been long.
=> Fix for several potential NullReferenceException cases.

Transports/com.mlapi.contrib.transport.litenetlib/Runtime/LiteNetLibTransport.cs
message buffer can change its size if lower than receive length data, but because variable data already assign from message buffer before checking, it will cause out of bounds.
=> fix data out of bounds

Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/Photon/PhotonRealtime/Code/Unity/Editor/Wizard/scripts/WizardWindow.cs
PhotonPeer.ClientVersion is obsoleted. from now on use PhotonPeer.Version.
=> Fix obsoleted code.

Transports/com.mlapi.contrib.transport.photon-realtime/Runtime/PhotonRealtimeTransport.cs
Seems there was a simple mistake made where it would only generate a random username if there was a nickname given, rather than the other way round.
=> fix: Photon generates a random nickname if none is provided

Transports/com.community.netcode.transport.photon-realtime/Runtime/PhotonRealtimeTransport.Matchmaking.cs, Transports/com.community.netcode.transport.photon-realtime/Runtime/PhotonRealtimeTransport.Room.cs
Connect event ids on the client now contain the hosts peer id instead of the clients own id. This results in the Photon Realtime transport behaving similar to the UNet and UnityTransport and allows it to work with [#1368](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/pull/1368)
Tested on Boss Room `fix/ngo-pre.3` branch (#483194dd749e062fcedd58d3fac43caeb0d7587b) with 1 host + 2 clients on same machine able to connect to the lobby select a character and walk around in the game using Photon Realtime Transport
=> fix(1.0.0-pre.3): Photon Transport connect event id assignment

com.community.netcode.extensions/package.json
The extension package had invalid (non existing) dependencies which caused errors when installing the package while the UTP adapter package was not installed already.
=> fix: extension package dependencies

Transports/com.community.netcode.transport.steamnetworking/CHANGELOG.md, Transports/com.community.netcode.transport.steamnetworking/Runtime/SteamNetworkingTransport.cs, Transports/com.community.netcode.transport.steamnetworking/package.json
Channels weren't correctly ported to the 1.0.0 version. The `NetcodeData` channel was never polled in the `Poll` function so Netcode for GameObjects was unable to send data.
=> fix: Fix channel implementation in steamnetworking transport.

com.community.netcode.extensions/CHANGELOG.md, com.community.netcode.extensions/Runtime/LagCompensation/FixedQueue.cs, com.community.netcode.extensions/Runtime/LagCompensation/FixedQueue.cs.meta, com.community.netcode.extensions/package.json
Adds the FixedQueue to the extensions package. (Was silently removed as a breaking change in the 1.0.0-pre4 release on purpose [1498](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/pull/1398))
Fixes #140
=> fix: Add fixedqueue back

Transports/com.community.netcode.transport.facepunch/Runtime/FacepunchTransport.cs
This PR:
* Implements `NetworkTransport.GetCurrentRtt` by returning the `ConnectionStatus.Ping` value.
* Removes all garbage created when data is received from the low level Facepunch/Steamworks transport by using native `MemCpy`.
I've taken a look at a bunch of the other transports, and some could benefit from a similar `MemCpy` approach to avoiding GC.
=> Facepunch Transport returns RTT and no longer generates garbage for messages

com.community.netcode.extensions/Runtime/NetworkDictionary.meta, com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.cs, com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.cs.meta, com.community.netcode.extensions/Runtime/com.community.contrib.extensions.asmdef
I've readapted the old NetworkDictionary from before NGO 1.0.0 to use unmanaged memory and added stuff like the PreviousValue in the OnDictionaryChanged event to be on par with the NetworkList implementation.
=> feat: add renewed NetworkDictionary

Transports/com.community.netcode.transport.enet/Runtime/EnetTransport.cs, Transports/com.community.netcode.transport.facepunch/Runtime/FacepunchTransport.cs, Transports/com.community.netcode.transport.litenetlib/Runtime/LiteNetLibTransport.cs, Transports/com.community.netcode.transport.ruffles/Runtime/RufflesTransport.cs, Transports/com.community.netcode.transport.steamnetworking/Runtime/SteamNetworkingTransport.cs, Transports/com.community.netcode.transport.template/Runtime/TemplateTransport.cs, Transports/com.community.netcode.transport.websocket/Runtime/WebSocketTransport.cs
Update all transports (except Photon, which is already fixed) to the new method signature of `NetworkTransport.Initialize` (it now takes an optional `NetworkManager` as an argument).
=> Update to new NetworkTransport.Initialize signature

Transports/com.community.netcode.transport.facepunch/Runtime/FacepunchTransport.cs
Revert the add of quickstatus (#143) which was used to fetch the ping for connected clients. This API is currently not in a release version of Facepunch. We can add it back later once it is supported.
=> revert: remove quickstatus (#143)

com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.asmref, com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.asmref.meta, com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.cs, com.community.netcode.extensions/Runtime/NetworkDictionary/README.md
`internal static void Write` and `internal static void Read` methods of the `public static class NetworkVariableSerialization<T>` (NetworkVariableSerialization.cs) of the NGO's package have to be made `public` in order to make this implementation work.
OR
You can add an Assembly definition reference (.asmref) next to this file pointing to the NGO's package. It'll make Unity consider this file as it was part of the NGO's package and effectively give it access to all NGO's `internal` methods.
=> fix: port NetworkDictionary to 1.0.0 (stable)

Transports/com.community.netcode.transport.facepunch/Runtime/FacepunchTransport.cs
This small little fix follows suit in the other places where connectionManager, and uses the null check ? `connectionManager?.Connection.Close();` as other places do. This fixes the NRE (NullReferenceException) that happens after play mode on NetCode 1.2.0 it seems. :)
=> Fix NRE (NullReferenceException)

com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.cs
NetworkDictionary was not marking the underlying NetworkBehaviour as dirty, and hence its changes were never processed.
=> Fix NetworkDictionary not working

Transports/com.community.netcode.transport.websocket/Runtime/JSWebSocketClient.jslib, Transports/com.community.netcode.transport.websocket/Runtime/NativeWebSocketClient.cs, Transports/com.community.netcode.transport.websocket/Runtime/WebSocketClientFactory.cs, Transports/com.community.netcode.transport.websocket/Runtime/WebSocketTransport.cs
Adjusted web socket transport so it can be re-used multiple times and not rely on static fields to manage state.
This way a player can connect, disconnect, and reconnect without having to re-create the web socket transport.
Also included changes from PR #174 to change references in `JSWebSocketClient.jslib` to use `Module['dynCall_vii']` instead of `Runtime.dynCall('v', _, []);` to get around the error: `ReferenceError: Runtime is not defined`
Found that the variable `Runtime` no longer exists in more recent versions of the WebGL build for unity. Would it be best to make two versions of these calls based on a flag like if the unity build is before/after v2021.2 to decide if that flag should be used?
https://stackoverflow.com/questions/70411564/unity-webgl-throws-error-referenceerror-runtim …
=> fix: WebSocketTransport Re-use and Compatibility

Transports/com.community.netcode.transport.websocket/Runtime/WebSocketTransport.cs
This path was hardcoded to `/netcode` which is not necessary for websocket connections, and is an opinionated choice that breaks in certain reverse proxy configurations such as using domains per game server with certs for WSS connections from the browser.
The only way to use the transport in an actual professional setting is to fork and delete the path out of the code, which this lets the user do now without modifying the code.
Web sockets are not required to listen on any path at all. This allows users to delete the path but the default does not break backwards compatibility.
Using this in production for our unity re-write of https://rolltable.app
=> Add option to configure websocket path

Transports/com.community.netcode.transport.multipeer-connectivity/Editor/MultipeerConnectivityTransportBuildProcessor.cs, Transports/com.community.netcode.transport.multipeer-connectivity/LICENSE.md, Transports/com.community.netcode.transport.multipeer-connectivity/Runtime/MultipeerConnectivityTransport.cs
just updated the license file and added some file headers
=> updated license

Transports/com.community.netcode.transport.steamnetworkingsockets/Runtime/SteamNetworkingSocketsTransport.cs
with netcode for gameobjects 1.2.0, DisconnectLocalClient can get called without setting up serverUser when starting a host
fixed #192 for me
=> fix null reference exception in steam transport when shutting down a host

Transports/com.community.netcode.transport.facepunch/Runtime/FacepunchTransport.cs
This just makes sure to flush any pending messages before closing the connection.
=> fix: Flush pending messages server side when a client is disconnected

Transports/com.community.netcode.transport.facepunch/Runtime/Facepunch/Facepunch.Steamworks.Posix.dll.meta
Facepunch Steamworks assembly reference couldn't be found when I tried to use Facepunch transport on Fedora 38 with Unity 2021.3.23f1 installed. I fixed it by modifying the assembly's info and changing its platform settings (changed target OS from OSX to Any OS).
=> fix: Facepunch.Steamworks assembly reference couldn't be found

com.community.netcode.extensions/Runtime/NetworkObjectPool/NetworkObjectPool.cs
Basically it now works just like the ['official' version](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/Assets/Scripts/Infrastructure/NetworkObjectPool.cs).
* It's now a NetworkBehaviour, not a MonoBehaviour
* It's a singleton
* It uses the NetworkManager.Singleton instead of a m_NetworkManager
* It initializes the pool in OnNetworkSpawn instead of in Awake
=> NetworkObjectPool feature parity with the version in the Unity Multiplayer Samples Boss Room sample project

com.community.netcode.extensions/Runtime/NetworkDiscovery/NetworkDiscovery.cs
This is a fix for the issue mentioned in #193.
=> Fix "Invalid allocation label" exception in NetworkDiscovery.

com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.cs
updated the MarkNetworkObjectDirty() to adhere to v1.5.1
=> Fixed NetworkDictionary for v1.5.1

Transports/com.community.netcode.transport.photon-realtime/Runtime/com.community.netcode.transport.photon-realtime.asmdef
=> Fix Unity.Collections not being referenced in assembly for Photon Realtime Transport

Transports/com.community.netcode.transport.websocket/Runtime/Libraries/websocket-sharp/websocket-sharp/WebSocket.cs, Transports/com.community.netcode.transport.websocket/Runtime/NativeWebSocketClient.cs
When I was trying to use websocket to connect to server, I've noted that if I try to connect as client on an inexistant server, the code returned true and I was trying to do somme code with server whereas the connection was not realized.
I've determined that the function `Connect` in the `WebSocket` wlass of the WebSocket-Sharp library was returning void.
BUT, the inner function returned bool.
I've think to pass the bool up to the caller to have better control over the life cycle.
=> Feature/web socket.connect returns bool instead of void

com.community.netcode.extensions/Runtime/NetworkDictionary/NetworkDictionary.cs
changed usage of NetworkVariableSerialization read and write methods to use the new api. changed instances of m_NetworkBehaviour to GetBehaviour(). changed MarkNetworkObjectDirty() to use the base method  MarkNetworkBehaviourDirty() changed instances of NativeList<T>.ToArray() to define an Allocator to comply with newer api.
=> fix: updated network dictionary to work with newer versions of ngo
